"""initial bandi cards

Revision ID: 20260822_0001
Revises:
Create Date: 2026-08-22 15:44:48.120001
"""
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260822_0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rarity', sa.Integer(), nullable=False),
    sa.Column('yp', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('image_key', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rarity >= 1 AND rarity <= 5', name='ck_cards_rarity'),
    sa.CheckConstraint('weight IS NULL OR weight > 0', name='ck_cards_weight'),
    sa.CheckConstraint('yp >= 0', name='ck_cards_yp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_active'), 'cards', ['active'], unique=False)
    op.create_index(op.f('ix_cards_name'), 'cards', ['name'], unique=True)
    op.create_index(op.f('ix_cards_rarity'), 'cards', ['rarity'], unique=False)
    op.create_table('image_cleanup',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('image_key', sa.String(length=512), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_key')
    )
    op.create_table('notification_outbox',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recipient_discord_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_outbox_available_at'), 'notification_outbox', ['available_at'], unique=False)
    op.create_index(op.f('ix_notification_outbox_recipient_discord_id'), 'notification_outbox', ['recipient_discord_id'], unique=False)
    op.create_index(op.f('ix_notification_outbox_status'), 'notification_outbox', ['status'], unique=False)
    op.create_table('oauth_attempts',
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.Column('verifier', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('state_hash')
    )
    op.create_index(op.f('ix_oauth_attempts_expires_at'), 'oauth_attempts', ['expires_at'], unique=False)
    op.create_table('rarity_settings',
    sa.Column('rarity', sa.Integer(), nullable=False),
    sa.Column('probability', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('probability >= 0 AND probability <= 100', name='ck_rarity_probability'),
    sa.CheckConstraint('rarity >= 1 AND rarity <= 5', name='ck_rarity_settings_range'),
    sa.PrimaryKeyConstraint('rarity')
    )
    now = datetime.now(timezone.utc)
    rarity_settings = sa.table(
        'rarity_settings',
        sa.column('rarity', sa.Integer()),
        sa.column('probability', sa.Numeric(precision=7, scale=4)),
        sa.column('updated_at', sa.DateTime(timezone=True)),
    )
    op.bulk_insert(
        rarity_settings,
        [
            {'rarity': 1, 'probability': 45.0, 'updated_at': now},
            {'rarity': 2, 'probability': 30.0, 'updated_at': now},
            {'rarity': 3, 'probability': 19.3, 'updated_at': now},
            {'rarity': 4, 'probability': 5.1, 'updated_at': now},
            {'rarity': 5, 'probability': 0.6, 'updated_at': now},
        ],
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('global_name', sa.String(length=64), nullable=True),
    sa.Column('avatar_hash', sa.String(length=128), nullable=True),
    sa.Column('warning_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('accepts_gifts', sa.Boolean(), nullable=False),
    sa.Column('accepts_trades', sa.Boolean(), nullable=False),
    sa.Column('profile_synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('profile_sync_attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('profile_sync_error', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_discord_id'), 'users', ['discord_id'], unique=True)
    op.create_index(op.f('ix_users_global_name'), 'users', ['global_name'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('admin_audit',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audit_admin_id'), 'admin_audit', ['admin_id'], unique=False)
    op.create_table('draw_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.String(length=36), nullable=True),
    sa.Column('card_name', sa.String(length=100), nullable=False),
    sa.Column('card_rarity', sa.Integer(), nullable=False),
    sa.Column('card_yp', sa.Integer(), nullable=False),
    sa.Column('draw_day', sa.Date(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('drawn_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'draw_day', name='uq_draw_user_day'),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_draw_user_idempotency')
    )
    op.create_index(op.f('ix_draw_history_card_id'), 'draw_history', ['card_id'], unique=False)
    op.create_index(op.f('ix_draw_history_drawn_at'), 'draw_history', ['drawn_at'], unique=False)
    op.create_index(op.f('ix_draw_history_user_id'), 'draw_history', ['user_id'], unique=False)
    op.create_table('draw_states',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pulls_since_four_plus', sa.Integer(), nullable=False),
    sa.Column('pulls_since_five', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('gifts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.String(length=36), nullable=True),
    sa.Column('card_name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('sender_yp_change', sa.Integer(), nullable=False),
    sa.Column('receiver_yp_change', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_gift_quantity'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sender_id', 'idempotency_key', name='uq_gift_sender_idempotency')
    )
    op.create_index(op.f('ix_gifts_receiver_id'), 'gifts', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_gifts_sender_id'), 'gifts', ['sender_id'], unique=False)
    op.create_table('inventory',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_inventory_quantity'),
    sa.CheckConstraint('reserved_quantity <= quantity', name='ck_inventory_reserved_available'),
    sa.CheckConstraint('reserved_quantity >= 0', name='ck_inventory_reserved_nonnegative'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'card_id')
    )
    op.create_table('probability_audit',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('before_json', sa.Text(), nullable=False),
    sa.Column('after_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_rooms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inviter_id', sa.Integer(), nullable=False),
    sa.Column('invitee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('offer_version', sa.Integer(), nullable=False),
    sa.Column('inviter_accepted_version', sa.Integer(), nullable=True),
    sa.Column('invitee_accepted_version', sa.Integer(), nullable=True),
    sa.Column('reconnect_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invitee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trade_active_participants', 'trade_rooms', ['status', 'inviter_id', 'invitee_id'], unique=False)
    op.create_index(op.f('ix_trade_rooms_invitee_id'), 'trade_rooms', ['invitee_id'], unique=False)
    op.create_index(op.f('ix_trade_rooms_inviter_id'), 'trade_rooms', ['inviter_id'], unique=False)
    op.create_index(op.f('ix_trade_rooms_reconnect_deadline'), 'trade_rooms', ['reconnect_deadline'], unique=False)
    op.create_index(op.f('ix_trade_rooms_status'), 'trade_rooms', ['status'], unique=False)
    op.create_table('web_sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_index(op.f('ix_web_sessions_expires_at'), 'web_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_web_sessions_user_id'), 'web_sessions', ['user_id'], unique=False)
    op.create_table('websocket_tickets',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_index(op.f('ix_websocket_tickets_expires_at'), 'websocket_tickets', ['expires_at'], unique=False)
    op.create_index(op.f('ix_websocket_tickets_user_id'), 'websocket_tickets', ['user_id'], unique=False)
    op.create_table('five_star_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('draw_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['draw_id'], ['draw_history.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draw_id')
    )
    op.create_index(op.f('ix_five_star_events_card_id'), 'five_star_events', ['card_id'], unique=False)
    op.create_index(op.f('ix_five_star_events_created_at'), 'five_star_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_five_star_events_user_id'), 'five_star_events', ['user_id'], unique=False)
    op.create_table('trade_offers',
    sa.Column('room_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_trade_offer_quantity'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['trade_rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id', 'user_id', 'card_id')
    )
    op.create_table('trade_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('room_id', sa.String(length=36), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('card_id', sa.String(length=36), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['trade_rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_requests_room_id'), 'trade_requests', ['room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_requests_room_id'), table_name='trade_requests')
    op.drop_table('trade_requests')
    op.drop_table('trade_offers')
    op.drop_index(op.f('ix_five_star_events_user_id'), table_name='five_star_events')
    op.drop_index(op.f('ix_five_star_events_created_at'), table_name='five_star_events')
    op.drop_index(op.f('ix_five_star_events_card_id'), table_name='five_star_events')
    op.drop_table('five_star_events')
    op.drop_index(op.f('ix_websocket_tickets_user_id'), table_name='websocket_tickets')
    op.drop_index(op.f('ix_websocket_tickets_expires_at'), table_name='websocket_tickets')
    op.drop_table('websocket_tickets')
    op.drop_index(op.f('ix_web_sessions_user_id'), table_name='web_sessions')
    op.drop_index(op.f('ix_web_sessions_expires_at'), table_name='web_sessions')
    op.drop_table('web_sessions')
    op.drop_index(op.f('ix_trade_rooms_status'), table_name='trade_rooms')
    op.drop_index(op.f('ix_trade_rooms_reconnect_deadline'), table_name='trade_rooms')
    op.drop_index(op.f('ix_trade_rooms_inviter_id'), table_name='trade_rooms')
    op.drop_index(op.f('ix_trade_rooms_invitee_id'), table_name='trade_rooms')
    op.drop_index('ix_trade_active_participants', table_name='trade_rooms')
    op.drop_table('trade_rooms')
    op.drop_table('probability_audit')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_gifts_sender_id'), table_name='gifts')
    op.drop_index(op.f('ix_gifts_receiver_id'), table_name='gifts')
    op.drop_table('gifts')
    op.drop_table('draw_states')
    op.drop_index(op.f('ix_draw_history_user_id'), table_name='draw_history')
    op.drop_index(op.f('ix_draw_history_drawn_at'), table_name='draw_history')
    op.drop_index(op.f('ix_draw_history_card_id'), table_name='draw_history')
    op.drop_table('draw_history')
    op.drop_index(op.f('ix_admin_audit_admin_id'), table_name='admin_audit')
    op.drop_table('admin_audit')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_global_name'), table_name='users')
    op.drop_index(op.f('ix_users_discord_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('rarity_settings')
    op.drop_index(op.f('ix_oauth_attempts_expires_at'), table_name='oauth_attempts')
    op.drop_table('oauth_attempts')
    op.drop_index(op.f('ix_notification_outbox_status'), table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_recipient_discord_id'), table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_available_at'), table_name='notification_outbox')
    op.drop_table('notification_outbox')
    op.drop_table('image_cleanup')
    op.drop_index(op.f('ix_cards_rarity'), table_name='cards')
    op.drop_index(op.f('ix_cards_name'), table_name='cards')
    op.drop_index(op.f('ix_cards_active'), table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###
